### ISSUE TITLE
Add aar to Maven Central

### ISSUE THREAD

**Issue by damianflannery** [ManuelPeinado/FadingActionBar#19]
It looks like you're already using Gradle. Accoding to http://gradleplease.appspot.com/ this library is available as an apklib but not aar. 

Would you mind adding it?

**Comment by ManuelPeinado** [comment]
I'm currently in the process of porting all my libs to AAR. So far I've
done so with GlassActionBar and MultiChoiceAdapter, and FadingActionBar
will be next. I expect to find some time to do it over the next couple of
weeks, so stay tuned. I know it could be done much faster, since as you say
I already have gradle support in the project, but I also want to
restructure the lib a little bit (adding support for actionbarcompat, among
other things).

**Comment by damianflannery** [comment]
Thanks; it's an excellent library. Keep up the good work :)

**Comment by ManuelPeinado** [comment]
Done in 3.0.0
